scheduler.interval.ms=300000
http.timeout.ms=15000

interest.service.url=http://zavainterestcalculator:8080
interest.service.endpoint=/api/batch/accrue-interest

statement.service.url=http://zavastatementservice:8080
statement.service.endpoint=/api/batch/generate-statements

reconciliation.service.url=http://zavaledger:8080
reconciliation.service.endpoint=/api/batch/reconcile-daily

db.url=jdbc:sqlserver://sqlserver:1433;databaseName=ZavaBankCore;encrypt=false;trustServerCertificate=true
db.username=sa
db.password=YourStrong!Passw0rd
